apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-web
spec:
  replicas: 2 # Runs on both your master and worker nodes
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
      - name: react-app
        # REPLACE this with your actual Docker Hub image from your GitHub Action
        image: rukevweubio/react-app:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"