apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
      - name: react-app
        image: rukevweubio/react-app: ca23a277f5901ea5abd95207e8b5fe4f796e6a1c
        ports:
        - containerPort: 80
        