apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80  
      nodePort: 30005 