apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: 80        # The port inside the cluster
      targetPort: 80  # The port the React app listens on
      nodePort: 30005 # The port you will use in your browser